#!/usr/bin/env bash
# Navigators - Clean Machine Test Script
# This script guides a developer/tester through the exact sequence required
# to validate the system on a completely fresh device.

echo "=================================================="
echo "    NAVIGATORS - CLEAN MACHINE VALIDATION FLOW    "
echo "=================================================="
echo ""
echo "This test ensures the entire product lifecycle works for a NEW user."
echo "Follow these steps manually on a clean Android device."
echo ""
echo "[STEP 1] INSTALLATION"
echo "  - Uninstall any existing version of the Navigators app."
echo "  - Transfer 'navigators-release.apk' to the device."
echo "  - Install the APK and launch it."
echo ""
read -p "Press Enter when you have reached the Onboarding screen..."

echo ""
echo "[STEP 2] PERMISSIONS & ONBOARDING"
echo "  - Verify that the app asks for Location and Activity Recognition."
echo "  - Grant permissions."
echo "  - Verify that the UI transitions to the Dashboard."
echo ""
read -p "Press Enter when Permissions are granted and you are on the Dashboard..."

echo ""
echo "[STEP 3] DIAGNOSTICS & SYSTEM HEALTH"
echo "  - In the Android app, go to Settings -> System Health."
echo "  - Run the diagnostic check. It should pass Sensors, GNSS, and AI Model checks."
echo "  - (Optional) Connect an External IMU via Bluetooth."
echo ""
read -p "Press Enter when Health Checks pass..."

echo ""
echo "[STEP 4] FIELD TEST NAVIGATION (WITH GNSS OUTAGE)"
echo "  - Tap 'Start Field Test'."
echo "  - Drive normally for 2 minutes (GNSS available)."
echo "  - Enter a tunnel or underground garage to force GNSS loss."
echo "  - Verify the UI indicates 'GNSS Lost - DR Active'."
echo "  - Continue driving for 1 minute."
echo "  - Exit the tunnel to regain GNSS."
echo "  - Verify the UI indicates 'GNSS Recovered'."
echo "  - Stop the Field Test."
echo ""
read -p "Press Enter when the Field Test is stopped..."

echo ""
echo "[STEP 5] CLOUD SYNC & WEB VERIFICATION"
echo "  - Ensure the device is connected to the internet."
echo "  - Open the Web Dashboard (http://localhost:8080)."
echo "  - Navigate to the 'Sessions' tab."
echo "  - Verify your new session appears in the list."
echo "  - Click on the session to view the Session Report."
echo "  - Verify that the report shows the GNSS Outage and AI Speed telemetry."
echo ""
read -p "Press Enter when you have verified the data on the Web Dashboard..."

echo ""
echo "=================================================="
echo "    VALIDATION COMPLETE                           "
echo "=================================================="
echo "If all steps succeeded, the Release Candidate is verified."
