version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: navigators_backend
    restart: always
    env_file:
      - ../.env.production
    ports:
      - "8000:8000"
    volumes:
      - ../navigators_cloud.db:/app/navigators_cloud.db
    networks:
      - navigators_net

  web:
    build:
      context: ..
      dockerfile: docker/web.Dockerfile
    container_name: navigators_web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - navigators_net

networks:
  navigators_net:
    driver: bridge
